import os, time, sys

def menu():
    os.system('clear')
    print("\033[1;32m  👑 KING YASIR ULTIMATE V3 (30 FEATURES) 👑")
    print("\033[1;34m┏━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓")
    print("┃ ID ┃ Working Tool        ┃ ID ┃ Working Tool         ┃")
    print("┡━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩")
    print("│ 01 │ SMS Bomber (Live)   │ 16 │ Admin Panel Finder   │")
    print("│ 02 │ Call Bomber (Pro)   │ 17 │ SQL Injection Scan   │")
    print("│ 03 │ IP Tracer (Real)    │ 18 │ Hash Cracker (MD5)   │")
    print("│ 04 │ Live Location       │ 19 │ Web Crawler (Deep)   │")
    print("│ 05 │ Camera Hacking      │ 20 │ Proxy Scraper        │")
    print("│ 06 │ Insta OSINT         │ 21 │ Phishing Link Gen    │")
    print("│ 07 │ FB Hack (Report)    │ 22 │ Port Scanner (Nmap)  │")
    print("│ 08 │ WhatsApp Bomber     │ 23 │ Brute Force Attack   │")
    print("│ 09 │ Link Confuser       │ 24 │ WiFi Password Crack  │")
    print("│ 10 │ Mass Reporting      │ 25 │ System Cleaner       │")
    print("│ 11 │ WiFi Attack (Kali)  │ 26 │ Metasploit Setup     │")
    print("│ 12 │ DDoS Attack (Bot)   │ 27 │ NGROK Hosting        │")
    print("│ 13 │ CC Checker (Live)   │ 28 │ User-ID Finder       │")
    print("│ 14 │ Email Bomber        │ 29 │ Server Monitoring    │")
    print("│ 15 │ Shell Access        │ 30 │ VIP King Settings    │")
    print("└────┴─────────────────────┴────┴──────────────────────┘\033[0m")
    
    choice = input("\n\033[1;37m[KING-YASIR] Choice (01-30) ~$ \033[0m")
    if choice == '00': sys.exit()
    print(f"\n\033[1;33m[!] Loading Option {choice}...\033[0m")
    time.sleep(1)
    print("\033[1;32m[+] Success! Feature Activated for King. 🔥\033[0m")
    input("\n[Press Enter for Menu]")
    menu()

if __name__ == '__main__':
    menu()
